// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzk96t6BMHOS57bF7wr7WPtxi-ajnoMpc',
    appId: '1:895091456713:web:a2fcab975cf718dfa52b18',
    messagingSenderId: '895091456713',
    projectId: 'asd-app-b4235',
    authDomain: 'asd-app-b4235.firebaseapp.com',
    storageBucket: 'asd-app-b4235.appspot.com',
    measurementId: 'G-Z88KQE3S71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9yLDJVZ66uKzcDIIiaRe6BCXNZLkcEHI',
    appId: '1:895091456713:android:d7ba5f9f32bb2d88a52b18',
    messagingSenderId: '895091456713',
    projectId: 'asd-app-b4235',
    storageBucket: 'asd-app-b4235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRYhLhyqw62T1UGiKhySPn7WIrH4RwE4',
    appId: '1:895091456713:ios:54cdf47fa6fe2db2a52b18',
    messagingSenderId: '895091456713',
    projectId: 'asd-app-b4235',
    storageBucket: 'asd-app-b4235.appspot.com',
    iosBundleId: 'com.example.autism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtRYhLhyqw62T1UGiKhySPn7WIrH4RwE4',
    appId: '1:895091456713:ios:54cdf47fa6fe2db2a52b18',
    messagingSenderId: '895091456713',
    projectId: 'asd-app-b4235',
    storageBucket: 'asd-app-b4235.appspot.com',
    iosBundleId: 'com.example.autism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzk96t6BMHOS57bF7wr7WPtxi-ajnoMpc',
    appId: '1:895091456713:web:8392dcd1a442072ba52b18',
    messagingSenderId: '895091456713',
    projectId: 'asd-app-b4235',
    authDomain: 'asd-app-b4235.firebaseapp.com',
    storageBucket: 'asd-app-b4235.appspot.com',
    measurementId: 'G-DVLXBVVYCV',
  );
}
